app = "synergeia-n8n"
primary_region = "syd"

[build]
  dockerfile = "Dockerfile"

[env]
  GENERIC_TIMEZONE = "Australia/Sydney"
  N8N_BASIC_AUTH_ACTIVE = "true"
  N8N_BASIC_AUTH_USER = "admin"
  N8N_BASIC_AUTH_PASSWORD = "securepassword"
  N8N_HOST = "0.0.0.0"
  N8N_PORT = "5678"
  WEBHOOK_TUNNEL_URL = "https://synergeia-n8n.fly.dev"

[http_service]
  internal_port = 5678
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
  
